<?php
/**
 * Created at: 21/06/2016 00:28
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelTask;

class ControllerTask extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelTask());

        // not null
        $this->addItem("taskID", false, "int", 11);
        $this->addItem("taskDescription", false, "text", null);
        $this->addItem("difficulty", false, "int", 2);

        // nullable
        $this->addItem("projectID", true, "int", 11);
        $this->addItem("employeeID", true, "int", 11);
        $this->addItem("roleID", true, "int", 11);
        $this->addItem("startDate", true, "date", null);
        $this->addItem("endDate", true, "date", null);
        $this->addItem("estimation", true, "int", 11);
    }
}