<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelDepartment;

class ControllerDepartment extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelDepartment());

        // bindings
        $this->addItem("departmentID", false, "int(11)");
        $this->addItem("title", false, "varchar(50)");
        $this->addItem("maxSize", false, "int(11)");
        $this->addItem("deptDescription", true, "text");
        $this->addItem("startDate", false, "date");
        $this->addItem("monthlyExpenses", false, "double");
    }
}