<?php
/**
 * Created at: 20/04/2016 13:09
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelEducation;

class ControllerEducation extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelEducation());

        // not null
        $this->addItem("educationID", false, "int", 11);
        $this->addItem("title", false, "varchar", 50);
        $this->addItem("startDate", false, "date", null);
        $this->addItem("endDate", false, "date", null);
        $this->addItem("degree", false, "varchar", 50);
        $this->addItem("employeeID", false, "int", 11);

        // nullable

    }
}