<?php
/**
 * Created at: 20/04/2016 13:09
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelProject;

class ControllerProject extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelProject());

        // not null
        $this->addItem("projectID", false, "int", 11);
        $this->addItem("title", false, "varchar", 50);
        $this->addItem("startDate", false, "date", null);
        $this->addItem("endDate", false, "date", null);
        $this->addItem("contractNumber", false, "varchar", 50);
        $this->addItem("pjDescription", false, "text", null);
        $this->addItem("budget", false, "double", null);
        $this->addItem("contactID", false, "int", 11);

        // nullable
        $this->addItem("departmentID", true, "int", 11);
    }
}