<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelContact;

class ControllerContact extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelContact());

        // bindings
        $this->addItem("contactID", false, "int(11)");
        $this->addItem("contactName", false, "varchar(50)");
        $this->addItem("phoneNumber", true, "varchar(13)");
        $this->addItem("faxNumber", true, "varchar(13)");
        $this->addItem("email", true, "varchar(50)");
        $this->addItem("physicalAddress", true, "varchar(75)");
    }
}