<?php
/**
 * Created at: 20/04/2016 13:27
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelSprint;

class ControllerSprint extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelSprint());

        // not null
        $this->addItem("sprintID", false, "int", 11);
        $this->addItem("projectID", false, "int", 11);
        $this->addItem("startDate", false, "date", null);
        $this->addItem("endDate", false, "date", null);

        // nullable

    }
}