<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelEducation;

class ControllerEducation extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelEducation());

        // bindings
        $this->addItem("educationID", false, "int(11)");
        $this->addItem("title", false, "varchar(50)");
        $this->addItem("startDate", false, "date");
        $this->addItem("endDate", false, "date");
        $this->addItem("degree", false, "varchar(50)");
        $this->addItem("employeeID", false, "int(11)");
    }
}