<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelProject;

class ControllerProject extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelProject());

        // bindings
        $this->addItem("projectID", false, "int(11)");
        $this->addItem("title", false, "varchar(50)");
        $this->addItem("startDate", false, "date");
        $this->addItem("endDate", false, "date");
        $this->addItem("contractNumber", false, "varchar(50)");
        $this->addItem("pjDescription", false, "text");
        $this->addItem("budget", false, "double");
        $this->addItem("departmentID", true, "int(11)");
        $this->addItem("contactID", false, "int(11)");
    }
}