<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelEmployee;

class ControllerEmployee extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelEmployee());

        // bindings
        $this->addItem("employeeID", false, "int(11)");
        $this->addItem("roleID", true, "int(11)");
        $this->addItem("account", false, "varchar(50)");
        $this->addItem("password", false, "varchar(64)");
        $this->addItem("managerID", true, "int(11)");
        $this->addItem("departmentID", true, "int(11)");
        $this->addItem("firstName", false, "varchar(50)");
        $this->addItem("middleInitial", true, "char(1)");
        $this->addItem("lastName", false, "varchar(50)");
        $this->addItem("title", false, "varchar(50)");
        $this->addItem("cnp", false, "varchar(13)");
        $this->addItem("salary", false, "double");
        $this->addItem("priorSalary", false, "double");
        $this->addItem("hireDate", false, "date");
        $this->addItem("terminationDate", true, "date");
        $this->addItem("administrator", false, "int(1)");
    }
}