<?php
/**
 * Created at: 21/06/2016 00:28
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelRole;

class ControllerRole extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelRole());

        // not null
        $this->addItem("roleID", false, "int", 11);
        $this->addItem("name", false, "varchar", 50);
        $this->addItem("averageSalary", false, "double", null);

        // nullable
        $this->addItem("jobDescription", true, "text", null);
    }
}