<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelRole;

class ControllerRole extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelRole());

        // bindings
        $this->addItem("roleID", false, "int(11)");
        $this->addItem("name", false, "varchar(50)");
        $this->addItem("jobDescription", true, "text");
        $this->addItem("averageSalary", false, "double");
    }
}