<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelSprint;

class ControllerSprint extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelSprint());

        // bindings
        $this->addItem("sprintID", false, "int(11)");
        $this->addItem("projectID", false, "int(11)");
        $this->addItem("startDate", false, "date");
        $this->addItem("endDate", false, "date");
    }
}