<?php
/**
 * Created at: 20/04/16 12:38
 * Generated by ControllerIndex.php
 */

namespace Controllers\Main\Models;

use Controllers\Main\ControllerCRUD;
use Models\Generated\ModelTask;

class ControllerTask extends ControllerCRUD
{
    public function __construct()
    {
        // constructor
        parent::__construct($this, new ModelTask());

        // bindings
        $this->addItem("taskID", false, "int(11)");
        $this->addItem("sprintID", true, "int(11)");
        $this->addItem("employeeID", true, "int(11)");
        $this->addItem("roleID", true, "int(11)");
        $this->addItem("startDate", true, "date");
        $this->addItem("endDate", true, "date");
        $this->addItem("taskDescription", false, "text");
        $this->addItem("difficulty", false, "int(2)");
        $this->addItem("estimation", true, "int(11)");
    }
}