<?php
/**
 * Created at: 01/04/16 12:31
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Task.
 * @package Models
 */
class ModelTask extends SmartModel
{
    /**
     * @var int $taskID
     */
    public $taskID;

    /**
     * @var int $sprintID
     */
    public $sprintID;

    /**
     * @var int $employeeID
     */
    public $employeeID;

    /**
     * @var int $roleID
     */
    public $roleID;

    /**
     * @var string $startDate
     */
    public $startDate;

    /**
     * @var string $endDate
     */
    public $endDate;

    /**
     * @var string $taskDescription
     */
    public $taskDescription;

    /**
     * @var int $difficulty
     */
    public $difficulty;

    /**
     * @var int|null $estimation
     */
    public $estimation;


    /**
     * ModelTask constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Tasks");
    }

}