<?php
/**
 * Created at: 01/04/16 12:08
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Department.
 * @package Models
 */
class ModelDepartment extends SmartModel
{
    public $departmentID;
    public $title;
    public $maxSize;
    public $deptDescription;
    public $startDate;
    public $monthlyExpenses;

    /**
     * ModelDepartment constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Departments");
    }

}