<?php
/**
 * Created at: 01/04/16 12:29
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Contact.
 * @package Models
 */
class ModelContact extends SmartModel
{
    /**
     * @var int $contactID
     */
    public $contactID;

    /**
     * @var string $contactName
     */
    public $contactName;

    /**
     * @var string|null $phoneNumber
     */
    public $phoneNumber;

    /**
     * @var string|null $faxNumber
     */
    public $faxNumber;

    /**
     * @var string|null $email
     */
    public $email;

    /**
     * @var string|null $physicalAddress
     */
    public $physicalAddress;


    /**
     * ModelContact constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Contacts");
    }

}