<?php
/**
 * Created at: 01/04/16 12:09
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Sprint.
 * @package Models
 */
class ModelSprint extends SmartModel
{
    public $sprintID;
    public $projectID;
    public $startDate;
    public $endDate;

    /**
     * ModelSprint constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Sprints");
    }

}