<?php
/**
 * Created at: 01/04/16 12:30
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Department.
 * @package Models
 */
class ModelDepartment extends SmartModel
{
    /**
     * @var int $departmentID
     */
    public $departmentID;

    /**
     * @var string $title
     */
    public $title;

    /**
     * @var int $maxSize
     */
    public $maxSize;

    /**
     * @var string|null $deptDescription
     */
    public $deptDescription;

    /**
     * @var string $startDate
     */
    public $startDate;

    /**
     * @var double $monthlyExpenses
     */
    public $monthlyExpenses;


    /**
     * ModelDepartment constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Departments");
    }

}