<?php
/**
 * Created at: 01/04/16 12:07
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Contact.
 * @package Models
 */
class ModelContact extends SmartModel
{
    public $contactID;
    public $contactName;
    public $phoneNumber;
    public $faxNumber;
    public $email;
    public $physicalAddress;

    /**
     * ModelContact constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Contacts");
    }

}