<?php
/**
 * Created at: 01/04/16 12:30
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Project.
 * @package Models
 */
class ModelProject extends SmartModel
{
    /**
     * @var int $projectID
     */
    public $projectID;

    /**
     * @var string $title
     */
    public $title;

    /**
     * @var string $startDate
     */
    public $startDate;

    /**
     * @var string $endDate
     */
    public $endDate;

    /**
     * @var string $contractNumber
     */
    public $contractNumber;

    /**
     * @var string $pjDescription
     */
    public $pjDescription;

    /**
     * @var double $budget
     */
    public $budget;

    /**
     * @var int|null $departmentID
     */
    public $departmentID;

    /**
     * @var int $contactID
     */
    public $contactID;


    /**
     * ModelProject constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Projects");
    }

}