<?php
/**
 * Created at: 01/04/16 12:08
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Project.
 * @package Models
 */
class ModelProject extends SmartModel
{
    public $projectID;
    public $title;
    public $startDate;
    public $endDate;
    public $contractNumber;
    public $pjDescription;
    public $budget;
    public $departmentID;
    public $contactID;

    /**
     * ModelProject constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Projects");
    }

}