<?php
/**
 * Created at: 01/04/16 12:08
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Education.
 * @package Models
 */
class ModelEducation extends SmartModel
{
    public $educationID;
    public $title;
    public $startDate;
    public $endDate;
    public $degree;
    public $employeeID;

    /**
     * ModelEducation constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Educations");
    }

}