<?php
/**
 * Created at: 01/04/16 12:08
 * Generated by migration.php
 */

namespace Models;

use SmartModel;

/**
 * Model Role.
 * @package Models
 */
class ModelRole extends SmartModel
{
    public $roleID;
    public $name;
    public $jobDescription;
    public $averageSalary;

    /**
     * ModelRole constructor.
     */
    public function __construct()
    {
        parent::__construct($this, "Roles");
    }

}